# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
      time: '01:00'
      timezone: America/Los_Angeles
    ignore:
      - dependency-name: '@radix-ui/react-dropdown-menu'
    groups:
      eslint:
        patterns:
          - '@eslint/*'
          - '@typescript-eslint/*'
          - 'typescript'
      solana-program-clients:
        patterns:
          - '@solana-program/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
      undici:
        patterns:
          - 'undici'
          - 'undici-types'
  - package-ecosystem: 'npm'
    directory: '/docs'
    schedule:
      interval: daily
      time: '01:00'
      timezone: America/Los_Angeles
    groups:
      eslint:
        patterns:
          - 'eslint*'
          - 'typescript'
      solana:
        patterns:
          - '@solana/*'
      solana-program-clients:
        patterns:
          - '@solana-program/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
      undici:
        patterns:
          - 'undici'
          - 'undici-types'
